name: Build and Release EXE (manual, auto-tag)

# 仅手动触发，用户在触发时填写 version（例如: 1.2.3 或 v1.2.3）
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. 1.2.3 or v1.2.3)'
        required: true
        default: '1.0.0'

# 需要写权限以便创建 tag & release
permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout repository (fetch tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies (PyInstaller + optional requirements)
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path 'requirements.txt') {
            pip install -r requirements.txt
          } else {
            Write-Host 'No requirements.txt found, skipping.'
          }

      - name: Build with PyInstaller (uses build.spec at repo root)
        shell: pwsh
        run: |
          pyinstaller --clean --noconfirm build.spec

      - name: Find built .exe
        id: find_exe
        shell: pwsh
        run: |
          $exe = Get-ChildItem -Path dist -Recurse -Filter *.exe -File | Select-Object -First 1
          if (-not $exe) {
            Write-Error "No .exe found in dist directory. Build may have failed."
            exit 1
          }
          echo "exe_path=$($exe.FullName)" >> $env:GITHUB_OUTPUT
          echo "exe_name=$($exe.Name)" >> $env:GITHUB_OUTPUT
          Write-Host "Found exe: $($exe.FullName)"

      - name: Compose tag name (prepend v if needed)
        id: compose_tag
        shell: pwsh
        run: |
          $input = "${{ github.event.inputs.version }}"
          if ($input.StartsWith('v')) {
            $tag = $input
          } else {
            $tag = "v$input"
          }
          echo "TAG=$tag" >> $env:GITHUB_ENV
          Write-Host "Computed TAG: $tag"

      - name: Ensure tag does not already exist && create & push tag
        shell: pwsh
        env:
          TAG: ${{ env.TAG }}
        run: |
          Write-Host "Checking if tag $env:TAG exists on remote..."
          $exists = git ls-remote --tags origin $env:TAG
          if ($exists) {
            Write-Error "Tag $env:TAG already exists on remote. Aborting to avoid overwrite."
            exit 1
          }
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a $env:TAG -m "Release $env:TAG"
          # Ensure we can push using the checked-out credentials (actions/checkout persist-credentials)
          git push origin $env:TAG
          Write-Host "Tag $env:TAG created and pushed."

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.TAG }}
          release_name: ${{ env.TAG }}
          body: "Release ${{ env.TAG }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload EXE as release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_exe.outputs.exe_path }}
          asset_name: ${{ steps.find_exe.outputs.exe_name }}
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
